add check for bc & add ./castly info

diff --git a/castly b/castly
--- a/castly
+++ b/castly
@@ -3,11 +3,53 @@
 #load the hex into something i can work with
 MYHEX=$1
 
-#check for errors
-if ! [[ ${#MYHEX} == 6 && $2 =~ ^("light"|"dark"|"titlelight"|"titledark"|"sidebarlight"|"sidebardark"|"bothlight"|"bothdark"|"no")$ ]]; then
-	printf "usage: castly <hex> <mode> <amount> <titlebar amount> <sidebar amount>\n\nhex color should NOT contain #\nall 3 amounts are optional (default 0.1, 0.2, 0.175)\n\nmodes: light, dark, titlelight, titledark, sidebarlight, sidebardark, bothlight, bothdark, no\n  title<light/dark>: tint the selection accent color & the titlebar\n  sidebar<light/dark>: tint the selection accent color & the sidebar\n  both<light/dark>: tint the titlebar, sidebar, & the selection accent color\n  no: only change the selection accent color\n\nexample: castly 95AEA3 bothlight 0.2 0.6 0.4\nor: castly 95AEA3 light\n\n\033[31;4mTHIS PROGRAM WILL DELETE YOUR GTK.CSS\033[0m. \033[31;4mMAKE A BACKUP\033[0m!!!!!!!!!!!!!!!!!!\n"
+if [[ $1 == "info" ]]; then
+	printf "castly is made by me; rgbmew, aka cthrn\n"
+	printf "https://github.com/rgbmew/castly/\n"
+	printf "my website: https://rgbmew.neocities.org/\n"
+	printf "and if you appreciate my work, consider giving me money via bandcamp LOL https://cthrn.bandcamp.com/\n\n"
+	printf "i wanted a simple way to change my accent color on GNOME, as the PR for custom accent colors is essentially dead, and alternatives like Gradience or Material You are just too complicated, and too dependency-heavy for my liking\n\n"
+	printf "castly requires very few packages, just \033[1mbash\033[0m, \033[1mgnu utils\033[0m, and \033[1mbc\033[0m\n\n\n"
+	printf "Q: It works on GTK4 apps, but not adw-gtk3; what shall i do\?!\?!\?\?!\?!\n"
+	printf "A: symlink ~/.config/gtk-4.0/gtk.css to ~/.config/gtk-3.0/gtk.css, and everything will work automatically :)\n\n"
+	printf "Q: It works on natively-installed apps, but not flatpaks\?!\?!\?\?!\?!\n"
+	printf "A: flatpak override --user --filesystem=xdg-config/gtk-3.0:ro --filesystem=xdg-config/gtk-4.0:ro\n\n"
+	printf "Q: What's a good app for generating hex codes for my wallpaper?\n"
+	printf "A: I really like Paleta, in combination with Eyedropper, if I need more shades of the same color.\n"
+	printf "https://github.com/nate-xyz/paleta\n"
+	printf "https://github.com/FineFindus/eyedropper\n\n\n"
+	printf "known limitations that im unlikely to fix myself (consider submitting a PR!):\n"
+	printf " - GNOME Shell doesn't use the accent color (i would have to compile an entire shell theme, too many dependencies)\n"
+	printf " - you have to reload all of your apps for new accent colors to take effect\n"
+	printf "(more info - https://gitlab.gnome.org/GNOME/gtk/-/issues/3409)\n"
+	printf " - apps that force dark mode may look weird on light themes\n"
+	printf " - accent colors may not work on non-gtk apps, for example Telegram or KolourPaint\n\n"
+	printf "THE SOFTWARE IS PROVIDED “AS IS” or some shit idk im not a lawyer\n"
 	exit
 fi
+
+#check for errors
+if ! [[ ${#MYHEX} == 6 && $2 =~ ^("light"|"dark"|"titlelight"|"titledark"|"sidebarlight"|"sidebardark"|"bothlight"|"bothdark"|"no")$ ]]; then
+	printf "usage: castly <hex> <mode> <amount> <titlebar amount> <sidebar amount>\n\n"
+	printf "hex color should NOT contain #\n"
+	printf "all 3 amounts are optional (default 0.1, 0.2, 0.175)\n\n"
+	printf "modes: light, dark, titlelight, titledark, sidebarlight, sidebardark, bothlight, bothdark, no\n"
+	printf "  title<light/dark>: tint the selection accent color & the titlebar\n"
+	printf "  sidebar<light/dark>: tint the selection accent color & the sidebar\n"
+	printf "  both<light/dark>: tint the titlebar, sidebar, & the selection accent color\n"
+	printf "  no: only change the selection accent color\n\n"
+	printf "example: castly 95AEA3 bothlight 0.2 0.6 0.4\n"
+	printf "or: castly 95AEA3 light\n\n"
+	printf "\033[31;4mTHIS PROGRAM WILL DELETE YOUR GTK.CSS\033[0m. \033[31;4mMAKE A BACKUP\033[0m!!!!!!!!!!!!!!!!!!\n\n"
+	printf "you can also run \"castly info\" for more information about castly!\n"
+	exit
+fi
+
+if ! command -v bc &> /dev/null then
+    echo "bc not found, please install bc from your package manager\n\n(for example, sudo apt install bc, for debian-based distros)\n"
+    exit 1
+fi
+
 
 #I STOLE THIS HEX CONVERSION CODE FROM @nberlette ON GITHUB. THANK YOU FOR NOT SUING ME EVEN THOUGH I DIDNT ASK FOR PERMISSION
 function hex() {
